<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-22T05:36:23Z" name="Default suite" finished-at="2022-09-22T05:36:26Z" duration-ms="3516">
    <groups>
    </groups>
    <test started-at="2022-09-22T05:36:23Z" name="Default test" finished-at="2022-09-22T05:36:26Z" duration-ms="3516">
      <class name="DataDrivenTesting.DataDriven_AddNewEmployee">
        <test-method signature="AddEmployeeData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:DataDrivenTesting.DataDriven_AddNewEmployee@2b175c00]" started-at="2022-09-22T05:36:23Z" name="AddEmployeeData" data-provider="employeedata" finished-at="2022-09-22T05:36:25Z" duration-ms="1845" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rakesh]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[20000.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[20.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddEmployeeData -->
        <test-method signature="AddEmployeeData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:DataDrivenTesting.DataDriven_AddNewEmployee@2b175c00]" started-at="2022-09-22T05:36:25Z" name="AddEmployeeData" data-provider="employeedata" finished-at="2022-09-22T05:36:26Z" duration-ms="608" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mohan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10000.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[21.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [429]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at DataDrivenTesting.DataDriven_AddNewEmployee.AddEmployeeData(DataDriven_AddNewEmployee.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddEmployeeData -->
        <test-method signature="AddEmployeeData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:DataDrivenTesting.DataDriven_AddNewEmployee@2b175c00]" started-at="2022-09-22T05:36:26Z" name="AddEmployeeData" data-provider="employeedata" finished-at="2022-09-22T05:36:26Z" duration-ms="578" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Shalini]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[21000.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[22.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddEmployeeData -->
      </class> <!-- DataDrivenTesting.DataDriven_AddNewEmployee -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
